
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-07-31T12:36:03-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "740698232e568ce9c0e9dd2faa9a71f87ae603f8",
 "version": "1.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
